{% set name = "stone" %}
{% set version = "3.3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dropbox/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: e9a54a81208ac2f3724523c3007492ad3cdb9b6a3eb69ad0d3eac94b1a2e0d69
  patches:
    - patches/0001-avoid-strict-pinning.patch

build:
  number: 0
  entry_points:
    - stone=stone.cli:main
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - m2-patch  # [win]
    - patch     # [not win]
  host:
    - pip
    # No need strict pinning
    - pytest-runner >=5.3.2
    - python
    - setuptools
    - wheel
  run:
    - python
    - ply >=3.4
    - six >=1.12.0
    - packaging >=21.0
    - jinja2 >=3.0.3

test:
  source_files:
    - test
  imports:
    - stone
    - stone.backends
    - stone.backends.python_rsrc
    - stone.frontend
    - stone.ir
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - stone --help
    # test_whitespace is skipped on windows because of `InvalidSpec('Indent is not divisible by 4.', 5, 'ns1.stone')`
    - pytest test -k "not test_whitespace"  # [win]
    - pytest test  # [not win]
  requires:
    - pip
    - pytest <7
    - mock >=2.0.0,<5.0

about:
  home: https://www.dropbox.com/developers
  summary: Stone is an interface description language (IDL) for APIs.
  description: Stone is an interface description language (IDL) for APIs.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/dropbox/stone
  doc_url: https://github.com/dropbox/stone/tree/main/docs

extra:
  recipe-maintainers:
    - cjmartian
    - BastianZim
  skip-lints:
    - invalid_url
