{% set name = "stone" %}
{% set version = "3.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dropbox/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: dc5aff3fad1333188d4ddb4eee0a19d31e6262bb3cdf10c0bbdaeb309ff91a52

build:
  number: 0
  entry_points:
    - stone=stone.cli:main
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - pytest-runner ==5.2.0
    - python
    - setuptools
    - wheel
  run:
    - ply >=3.4
    - python
    - six >=1.3.0

test:
  imports:
    - stone
    - stone.backends
    - stone.backends.python_rsrc
    - stone.frontend
    - stone.ir
  requires:
    - pip
    - pytest <7
    - mock>=2.0.0,<5.0
  source_files:
    - test
  commands:
    - pip check
    - stone --help
    - pytest test

about:
  home: https://www.dropbox.com/developers
  summary: Stone is an interface description language (IDL) for APIs.
  description: Stone is an interface description language (IDL) for APIs.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/dropbox/stone
  doc_url: https://github.com/dropbox/stone/tree/main/docs

extra:
  recipe-maintainers:
    - cjmartian
    - BastianZim
